export const bundleData = {
  bundles: [
    {
      id: "bundle_3days",
      name: "3 Days Plan",
      description:
        "Tasty and balanced meals for 3 days — perfect for short meal prep cycles.",
      category: "veg",
      price: 399,
      bundleImage:
        "",
      totalNutrition: {
        calories: 3240,
        protein: 102,
        carbs: 516,
        fat: 72,
      },
      days: [
        {
          day: "Monday",
          menuName: "Limited Meals",
          items: [
            {
              itemName: "Steamed Rice",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Fluffy white rice cooked to perfection.",
              imageUrl: "https://example.com/items/steamed-rice.jpg",
              nutrition: { calories: 250, protein: 4, carbs: 54, fat: 0.5 },
            },
            {
              itemName: "Chapati",
              quantity: 2,
              uom: "pcs",
              category: "veg",
              description: "Soft wheat chapatis cooked on a flat griddle.",
              imageUrl: "https://example.com/items/chapati.jpg",
              nutrition: { calories: 200, protein: 6, carbs: 40, fat: 3 },
            },
            {
              itemName: "Vegetable Curry",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description:
                "Mixed seasonal vegetables simmered in rich curry sauce.",
              imageUrl: "https://example.com/items/vegetable-curry.jpg",
              nutrition: { calories: 180, protein: 5, carbs: 15, fat: 10 },
            },
            {
              itemName: "Sweet Pongal",
              quantity: 1,
              uom: "cup",
              category: "veg",
              description:
                "Sweetened rice and lentil dessert garnished with cashews.",
              imageUrl: "https://example.com/items/sweet-pongal.jpg",
              nutrition: { calories: 220, protein: 4, carbs: 45, fat: 5 },
            },
          ],
          totalNutrition: { calories: 850, protein: 19, carbs: 154, fat: 18.5 },
        },
        {
          day: "Tuesday",
          menuName: "Classic Combo",
          items: [
            {
              itemName: "Jeera Rice",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Aromatic basmati rice flavored with cumin seeds.",
              imageUrl: "https://example.com/items/jeera-rice.jpg",
              nutrition: { calories: 260, protein: 5, carbs: 55, fat: 2 },
            },
            {
              itemName: "Dal Tadka",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description:
                "Yellow lentils tempered with ghee, garlic, and spices.",
              imageUrl: "https://example.com/items/dal-tadka.jpg",
              nutrition: { calories: 210, protein: 10, carbs: 20, fat: 8 },
            },
            {
              itemName: "Papad",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Crispy roasted lentil wafer.",
              imageUrl: "https://example.com/items/papad.jpg",
              nutrition: { calories: 80, protein: 2, carbs: 7, fat: 4 },
            },
            {
              itemName: "Gulab Jamun",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Soft milk-based dumpling soaked in sugar syrup.",
              imageUrl: "https://example.com/items/gulab-jamun.jpg",
              nutrition: { calories: 190, protein: 3, carbs: 30, fat: 6 },
            },
          ],
          totalNutrition: { calories: 740, protein: 20, carbs: 112, fat: 20 },
        },
        {
          day: "Wednesday",
          menuName: "Special Veg Meal",
          items: [
            {
              itemName: "Veg Biryani",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description:
                "Fragrant basmati rice layered with spiced vegetables.",
              imageUrl: "https://example.com/items/veg-biryani.jpg",
              nutrition: { calories: 300, protein: 8, carbs: 55, fat: 7 },
            },
            {
              itemName: "Raita",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description: "Yogurt mixed with cucumber and mild spices.",
              imageUrl: "https://example.com/items/raita.jpg",
              nutrition: { calories: 120, protein: 5, carbs: 10, fat: 6 },
            },
            {
              itemName: "Paneer Curry",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description: "Cottage cheese cubes in creamy tomato gravy.",
              imageUrl: "https://example.com/items/paneer-curry.jpg",
              nutrition: { calories: 250, protein: 12, carbs: 10, fat: 15 },
            },
            {
              itemName: "Ladoo",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Traditional sweet made with gram flour and ghee.",
              imageUrl: "https://example.com/items/ladoo.jpg",
              nutrition: { calories: 180, protein: 3, carbs: 25, fat: 8 },
            },
          ],
          totalNutrition: { calories: 850, protein: 28, carbs: 100, fat: 36 },
        },
      ],
    },
    {
      id: "bundle_5days",
      name: "5 Days Plan",
      description: "Healthy and satisfying meals for your work week.",
      category: "mix",
      price: 599,
      bundleImage: "",
      totalNutrition: {
        calories: 4430,
        protein: 119,
        carbs: 580,
        fat: 135,
      },
      days: [
        {
          day: "Monday",
          menuName: "Limited Meals",
          items: [
            {
              itemName: "White Rice",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Simple, fluffy white rice.",
              imageUrl:
                "https://res.cloudinary.com/dgfaeq5fm/image/upload/v1761586514/image_1_wrzkxz.png",
              nutrition: { calories: 240, protein: 4, carbs: 53, fat: 0.4 },
            },
            {
              itemName: "Chapati",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Whole wheat flatbread, lightly roasted.",
              imageUrl: "https://example.com/items/chapati.jpg",
              nutrition: { calories: 100, protein: 3, carbs: 20, fat: 1 },
            },
            {
              itemName: "Chicken Vada",
              quantity: 2,
              uom: "pcs",
              category: "non-veg",
              description:
                "Deep-fried chicken patties with South Indian spices.",
              imageUrl: "https://example.com/items/chicken-vada.jpg",
              nutrition: { calories: 400, protein: 20, carbs: 15, fat: 25 },
            },
            {
              itemName: "Kesari",
              quantity: 1,
              uom: "cup",
              category: "veg",
              description: "Saffron semolina dessert with nuts and ghee.",
              imageUrl: "https://example.com/items/kesari.jpg",
              nutrition: { calories: 250, protein: 4, carbs: 45, fat: 8 },
            },
          ],
          totalNutrition: { calories: 990, protein: 31, carbs: 133, fat: 34.4 },
        },
        {
          day: "Tuesday",
          menuName: "South Indian Special",
          items: [
            {
              itemName: "Curd Rice",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Refreshing yogurt rice with curry leaves.",
              imageUrl: "https://example.com/items/curd-rice.jpg",
              nutrition: { calories: 280, protein: 8, carbs: 52, fat: 4 },
            },
            {
              itemName: "Pickle",
              quantity: 1,
              uom: "tsp",
              category: "veg",
              description: "Tangy and spicy lemon pickle.",
              imageUrl: "https://example.com/items/pickle.jpg",
              nutrition: { calories: 30, protein: 0, carbs: 2, fat: 2 },
            },
            {
              itemName: "Medu Vada",
              quantity: 2,
              uom: "pcs",
              category: "veg",
              description: "Crispy lentil donuts, golden fried.",
              imageUrl: "https://example.com/items/medu-vada.jpg",
              nutrition: { calories: 350, protein: 12, carbs: 40, fat: 18 },
            },
            {
              itemName: "Mysore Pak",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Soft and rich sweet made from ghee and gram flour.",
              imageUrl: "https://example.com/items/mysore-pak.jpg",
              nutrition: { calories: 250, protein: 4, carbs: 30, fat: 12 },
            },
          ],
          totalNutrition: { calories: 910, protein: 24, carbs: 124, fat: 36 },
        },
        {
          day: "Wednesday",
          menuName: "North Indian Delights",
          items: [
            {
              itemName: "Rajma Chawal (Rice)",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Basmati rice served with creamy kidney bean curry.",
              imageUrl: "https://example.com/items/rajma-chawal.jpg",
              nutrition: { calories: 380, protein: 15, carbs: 65, fat: 8 },
            },
            {
              itemName: "Plain Yogurt",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description: "Homemade plain yogurt (Dahi).",
              imageUrl: "https://example.com/items/yogurt.jpg",
              nutrition: { calories: 100, protein: 6, carbs: 8, fat: 5 },
            },
            {
              itemName: "Aloo Paratha",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Whole wheat bread stuffed with spiced potatoes.",
              imageUrl: "https://example.com/items/aloo-paratha.jpg",
              nutrition: { calories: 220, protein: 5, carbs: 30, fat: 9 },
            },
            {
              itemName: "Kheer",
              quantity: 1,
              uom: "cup",
              category: "veg",
              description: "Rice pudding slow-cooked with milk and sugar.",
              imageUrl: "https://example.com/items/kheer.jpg",
              nutrition: { calories: 200, protein: 4, carbs: 35, fat: 5 },
            },
          ],
          totalNutrition: { calories: 900, protein: 30, carbs: 138, fat: 27 },
        },
        {
          day: "Thursday",
          menuName: "Coastal Special",
          items: [
            {
              itemName: "Lemon Rice",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description:
                "Fragrant rice seasoned with lemon juice and peanuts.",
              imageUrl: "https://example.com/items/lemon-rice.jpg",
              nutrition: { calories: 310, protein: 5, carbs: 60, fat: 5 },
            },
            {
              itemName: "Fish Fry (Surmai)",
              quantity: 1,
              uom: "pc",
              category: "non-veg",
              description: "Kingfish fillet marinated and shallow-fried.",
              imageUrl: "https://example.com/items/fish-fry.jpg",
              nutrition: { calories: 280, protein: 25, carbs: 5, fat: 18 },
            },
            {
              itemName: "Sambar",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description: "Lentil-based vegetable stew from South India.",
              imageUrl: "https://example.com/items/sambar.jpg",
              nutrition: { calories: 150, protein: 8, carbs: 20, fat: 3 },
            },
            {
              itemName: "Banana Halwa",
              quantity: 1,
              uom: "cup",
              category: "veg",
              description: "Sweet dessert made from ripe bananas and ghee.",
              imageUrl: "https://example.com/items/banana-halwa.jpg",
              nutrition: { calories: 210, protein: 2, carbs: 40, fat: 5 },
            },
          ],
          totalNutrition: { calories: 950, protein: 40, carbs: 125, fat: 31 },
        },
        {
          day: "Friday",
          menuName: "Weekend Starter",
          items: [
            {
              itemName: "Vegetable Pulao",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description: "Flavored rice cooked with mixed vegetables.",
              imageUrl: "https://example.com/items/veg-pulao.jpg",
              nutrition: { calories: 350, protein: 7, carbs: 60, fat: 8 },
            },
            {
              itemName: "Chicken Korma",
              quantity: 1,
              uom: "bowl",
              category: "non-veg",
              description: "Creamy and mildly spiced chicken curry.",
              imageUrl: "https://example.com/items/chicken-korma.jpg",
              nutrition: { calories: 300, protein: 22, carbs: 10, fat: 18 },
            },
            {
              itemName: "Green Salad",
              quantity: 1,
              uom: "bowl",
              category: "veg",
              description: "Fresh mix of cucumber, tomato, and onion.",
              imageUrl: "https://example.com/items/green-salad.jpg",
              nutrition: { calories: 50, protein: 2, carbs: 8, fat: 1 },
            },
            {
              itemName: "Ice Cream",
              quantity: 1,
              uom: "scoop",
              category: "veg",
              description: "A single scoop of vanilla or chocolate ice cream.",
              imageUrl: "https://example.com/items/ice-cream.jpg",
              nutrition: { calories: 180, protein: 3, carbs: 20, fat: 10 },
            },
          ],
          totalNutrition: { calories: 880, protein: 34, carbs: 98, fat: 37 },
        },
      ],
    },
    {
      id: "bundle_1month",
      name: "1 Month Plan",
      description: "Daily rotating menus for 30 days of healthy meals.",
      category: "mix",
      price: 1999,
      bundleImage: "",
      totalNutrition: {
        calories: 21500,
        protein: 600,
        carbs: 2900,
        fat: 750,
      },
      days: [
        {
          day: "Weekly Rotation",
          menuName: "Chef’s Weekly Special",
          items: [
            {
              itemName: "Rice Variety",
              quantity: 1,
              uom: "plate",
              category: "veg",
              description:
                "Different rice dishes each week like lemon rice or biryani.",
              imageUrl: "https://example.com/items/rice-variety.jpg",
              nutrition: { calories: 280, protein: 6, carbs: 55, fat: 3 },
            },
            {
              itemName: "Curry of the Day",
              quantity: 1,
              uom: "bowl",
              category: "non-veg",
              description:
                "Alternating between paneer, chicken, or fish curries.",
              imageUrl: "https://example.com/items/curry-of-the-day.jpg",
              nutrition: { calories: 350, protein: 20, carbs: 10, fat: 22 },
            },
            {
              itemName: "Snack",
              quantity: 1,
              uom: "pc",
              category: "veg",
              description: "Rotating snacks like samosa, pakora, or cutlet.",
              imageUrl: "https://example.com/items/snack.jpg",
              nutrition: { calories: 180, protein: 4, carbs: 20, fat: 8 },
            },
            {
              itemName: "Dessert",
              quantity: 1,
              uom: "cup",
              category: "veg",
              description: "Variety of traditional Indian desserts each day.",
              imageUrl: "https://example.com/items/dessert.jpg",
              nutrition: { calories: 220, protein: 3, carbs: 35, fat: 6 },
            },
          ],
          totalNutrition: { calories: 1030, protein: 33, carbs: 120, fat: 39 },
        },
      ],
    },
  ],
};
